package TypeRegistry

import oeEDeCyZ "github.com/j7mbo/Injector/Logger"
import rEcdKSnL "github.com/j7mbo/Injector/ouch/again"
import EqNCKgek "github.com/j7mbo/Injector/ouch/again/again"

func GetAutoGeneratedRegistry() map[string][]interface{} {
	registry := make(map[string][]interface{})

	registry["Logger.Logger"] = append(registry["Logger.Logger"], new(oeEDeCyZ.Logger))
	registry["again.Needthis"] = append(registry["again.Needthis"], new(rEcdKSnL.Needthis))
	registry["again.Parent"] = append(registry["again.Parent"], new(rEcdKSnL.Parent))
	registry["again.Needthis"] = append(registry["again.Needthis"], new(EqNCKgek.Needthis))
	return registry
}
